---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
      cloud: openstack
    register: server_info
  - name: Delete instances
    debug:
      var: server_info
