---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
      cloud: openstack
    register: server_info

  - name: Delete instances
    os_server:
      cloud: openstack
      name: "{{ __server.id }}"
      state: absent
    loop: "{{ server_info.openstack_servers }}"
    loop_control:
      loop_var: __server
