---
- name: Install load balancer packages
  package:
    name: "{{ payload }}"
    state: present

- name: Configure {{ payload }} load balancing
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart {{ payload }}

- name: Enable {{ payload }}
  service:
    name: "{{ payload }}"
    state: started
    enabled: true

