---
- name: Install {{ payload }}
  yum:
    name: "{{ payload }}"
    state: present
  notify: start {{ payload }}

- name: create web root dir
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: install index
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
  notify: start {{ payload }}
